version: '3.4'

services:
    rides-backend-master:
        build: rides
        command: sh -c "uvicorn server:app --host 0.0.0.0 --port 8000 --reload"
        ports:
            - "8001:8000"
    rides-backend-replica-a:
        build: rides
        command: sh -c "uvicorn server:app --host 0.0.0.0 --port 8000 --reload"
        ports:
            - "8002:8000"
    rides-backend-replica-b:
        build: rides
        command: sh -c "uvicorn server:app --host 0.0.0.0 --port 8000 --reload"
        ports:
            - "8003:8000"
    load-balancer:
        image: nginx:alpine
        ports:
            - 8000:80
        volumes:
            - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf